### ISSUE TITLE
UnboundLocalError: local variable 'game_ended' referenced before assignment

### ISSUE THREAD

**Issue by christiangfv** [aigagror/GymGo#10]
Hi, i have this problem with de Gym
Do you know something about this?

```
christianfu@MBPdeChristian GymGo % python3 demo.py
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    go_env.render(mode="terminal")
  File "/Users/christianfu/Documents/GitHub/Search_Algorithm/GymGo/gym_go/envs/go_env.py", line 163, in render
    print(self.__str__())
  File "/Users/christianfu/Documents/GitHub/Search_Algorithm/GymGo/gym_go/envs/go_env.py", line 153, in __str__
    return gogame.str(self.state_)
  File "/Users/christianfu/Documents/GitHub/Search_Algorithm/GymGo/gym_go/gogame.py", line 404, in str
    game_ended = game_ended(state)
UnboundLocalError: local variable 'game_ended' referenced before assignment
```

**Comment by cafe-tera** [comment]
same error

**Comment by aigagror** [comment]
fixed
