### ISSUE TITLE
RuntimeError: Canvas has not been attached

### ISSUE THREAD

**Issue by Gregory-Eales** [aigagror/GymGo#11]
```bash
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 656, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 992, in _event_size
    self.switch_to()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 328, in switch_to
    self.context.set_current()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\gl\win32.py", line 243, in set_current
    super(Win32Context, self).set_current()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\gl\base.py", line 327, in set_current
    raise RuntimeError('Canvas has not been attached')
RuntimeError: Canvas has not been attached
 ```

**Comment by aigagror** [comment]
Sorry for the late response. What version of pyglet are you using?
It's working for me, and I'm on version `1.5.16`

**Comment by aigagror** [comment]
I will close this issue for now. If you still find it's not working. Please reopen it
